// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEJnQl8tMtF2IjnPkwAS0WcTBlpoDxONE',
    appId: '1:911692709116:web:576caf7df92b2557b9ab79',
    messagingSenderId: '911692709116',
    projectId: 'otto-64f99',
    authDomain: 'otto-64f99.firebaseapp.com',
    storageBucket: 'otto-64f99.appspot.com',
    measurementId: 'G-09SB3XRPXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlK6AOXQ29G4r3RbS6Y9xuObuzKjqea08',
    appId: '1:911692709116:android:a34b78c869681db3b9ab79',
    messagingSenderId: '911692709116',
    projectId: 'otto-64f99',
    storageBucket: 'otto-64f99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo45rdCTQwqOWEgPaxglZ5SADuysB7k24',
    appId: '1:911692709116:ios:9a5649eee6ee89e4b9ab79',
    messagingSenderId: '911692709116',
    projectId: 'otto-64f99',
    storageBucket: 'otto-64f99.appspot.com',
    androidClientId: '911692709116-oa8d9scb5skkrvu661vtodj4uvccs35l.apps.googleusercontent.com',
    iosClientId: '911692709116-o8f9ntde35bj7bg48es2cash5hfa3om4.apps.googleusercontent.com',
    iosBundleId: 'com.example.otto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo45rdCTQwqOWEgPaxglZ5SADuysB7k24',
    appId: '1:911692709116:ios:9a5649eee6ee89e4b9ab79',
    messagingSenderId: '911692709116',
    projectId: 'otto-64f99',
    storageBucket: 'otto-64f99.appspot.com',
    androidClientId: '911692709116-oa8d9scb5skkrvu661vtodj4uvccs35l.apps.googleusercontent.com',
    iosClientId: '911692709116-o8f9ntde35bj7bg48es2cash5hfa3om4.apps.googleusercontent.com',
    iosBundleId: 'com.example.otto',
  );
}
